# Generated by Django 3.1.1 on 2021-07-15 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(default='Not Started', max_length=50)),
                ('seats', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conferences', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ManyToManyField(blank=True, related_name='joined_conferences', to=settings.AUTH_USER_MODEL)),
                ('speaker', models.ManyToManyField(blank=True, related_name='speaker_conferences', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ManyToManyField(blank=True, related_name='sponsored_conferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Conference',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_reviews', to='D3ViCE_Conference.conference')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
