# Generated by Django 3.1.1 on 2021-07-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_Conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='status',
            field=models.CharField(default='Upcoming', max_length=50),
        ),
    ]
