# Generated by Django 3.1.1 on 2021-07-09 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_User', '0002_host_participant_speaker_sponsor'),
        ('D3ViCE_Conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_conferences', to='D3ViCE_User.host'),
        ),
        migrations.AddField(
            model_name='conference',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, related_name='joined_conferences', to='D3ViCE_User.Participant'),
        ),
        migrations.AddField(
            model_name='conference',
            name='speaker',
            field=models.ManyToManyField(blank=True, null=True, related_name='joined_conferences', to='D3ViCE_User.Speaker'),
        ),
        migrations.AddField(
            model_name='conference',
            name='sponsor',
            field=models.ManyToManyField(blank=True, null=True, related_name='sponsored_conferences', to='D3ViCE_User.Sponsor'),
        ),
    ]
