# Generated by Django 3.1.1 on 2021-04-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_User', '0002_host_participant_secretary_speaker_sponsor'),
        ('D3ViCE_Conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='participant',
            field=models.ManyToManyField(to='D3ViCE_User.Participant'),
        ),
        migrations.AddField(
            model_name='conference',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='D3ViCE_User.sponsor'),
        ),
    ]
