# Generated by Django 3.1.1 on 2021-07-15 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('D3ViCE_Conference', '0002_auto_20210715_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='sponsor',
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=500)),
                ('company_description', models.CharField(max_length=500)),
                ('reason', models.CharField(max_length=500)),
                ('is_accepted', models.BooleanField(default=False)),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to='D3ViCE_Conference.conference')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
