# Generated by Django 3.1.1 on 2021-05-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_Conference', '0002_auto_20210406_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='is_created',
        ),
    ]
