# Generated by Django 3.1.1 on 2021-05-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_User', '0003_auto_20210519_1150'),
        ('D3ViCE_Conference', '0003_remove_conference_is_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, to='D3ViCE_User.Participant'),
        ),
    ]
