# Generated by Django 3.1.1 on 2021-09-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_Conference', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
