# Generated by Django 3.1.1 on 2021-07-09 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_User', '0003_auto_20210519_1150'),
        ('D3ViCE_Conference', '0004_auto_20210519_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_conferences', to='D3ViCE_User.organizer'),
        ),
        migrations.AddField(
            model_name='conference',
            name='speaker',
            field=models.ManyToManyField(blank=True, null=True, related_name='joined_conferences', to='D3ViCE_User.Speaker'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, related_name='joined_conferences', to='D3ViCE_User.Participant'),
        ),
        migrations.RemoveField(
            model_name='conference',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='conference',
            name='sponsor',
            field=models.ManyToManyField(blank=True, null=True, related_name='sponsored_conferences', to='D3ViCE_User.Sponsor'),
        ),
    ]
