# Generated by Django 3.1.1 on 2021-09-13 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('D3ViCE_Conference', '0005_question_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='intended_speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_speaker', to=settings.AUTH_USER_MODEL),
        ),
    ]
