# Generated by Django 3.1.1 on 2021-05-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_User', '0002_host_participant_secretary_speaker_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
