# Generated by Django 3.1.1 on 2021-07-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_User', '0002_auto_20210715_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_organizer',
            new_name='is_sponsor',
        ),
    ]
