# Generated by Django 3.1.1 on 2021-07-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_User', '0003_auto_20210715_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sponsor_name',
        ),
    ]
