# Generated by Django 3.1.1 on 2021-07-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_Conference', '0005_auto_20210709_1224'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('D3ViCE_User', '0003_auto_20210519_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('cost_per_month', models.FloatField()),
            ],
            options={
                'db_table': 'Plan',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Request',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.RenameModel(
            old_name='Host',
            new_name='Organizer',
        ),
        migrations.AlterModelTable(
            name='organizer',
            table='Organizer',
        ),
    ]
