# Generated by Django 3.1.1 on 2021-07-15 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_User', '0004_remove_profile_sponsor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 15)),
        ),
    ]
