# Generated by Django 3.1.1 on 2021-07-15 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_Conference', '0003_auto_20210715_2155'),
        ('D3ViCE_User', '0005_auto_20210715_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='conference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='D3ViCE_Conference.conference'),
        ),
        migrations.AddField(
            model_name='request',
            name='sponsorship',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='D3ViCE_Conference.sponsorship'),
        ),
    ]
