# Generated by Django 3.1.1 on 2021-07-15 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_User', '0006_auto_20210715_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='target',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_target', to=settings.AUTH_USER_MODEL),
        ),
    ]
