# Generated by Django 3.1.1 on 2021-07-15 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_Conference', '0003_auto_20210715_2155'),
        ('D3ViCE_User', '0007_request_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='D3ViCE_Conference.conference'),
        ),
        migrations.AlterField(
            model_name='request',
            name='sponsorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conference_sponsorships', to='D3ViCE_Conference.sponsorship'),
        ),
        migrations.AlterField(
            model_name='request',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_target', to=settings.AUTH_USER_MODEL),
        ),
    ]
