# Generated by Django 3.1.1 on 2021-09-05 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_User', '0009_auto_20210716_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.date(2021, 9, 5)),
        ),
    ]
