# Generated by Django 3.1.1 on 2021-09-09 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D3ViCE_User', '0010_auto_20210905_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.date(2021, 9, 9)),
        ),
    ]
